export enum HttpStatus {
  NOT_FOUND = 404,
  UNAUTHORIZED = 404,
  FORBIDDEN = 403,
  BAD_REQUEST = 400,
  BAD_GATEWAY = 502,
  OK = 200,
  CREATED = 201,
  TOO_MANY_REQUESTS = 429,
  INTERNAL_SERVER_ERROR = 500,
}
export enum HttpResultCode {
  NOT_FOUND = 'NOT_FOUND',
  OK = 'OK',
  UNAUTHORIZED = 'UNAUTHORIZED',
  CREATED = 'CREATED',
  EXPIRED_TIME = 'EXPIRED_TIME',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  BAD_REQUEST = 'BAD_REQUEST',
  FORBIDDEN = 'FORBIDDEN',
  BAD_GATEWAY = 'BAD_GATEWAY',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
