const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

async function main() {
  console.log('🏘️ Seeding Districts...');

  const districts = [
    // TP Hồ Chí Minh (code: 79)
    {
      code: '760',
      name: 'Quận 1',
      fullName: 'Quận 1',
      codeName: 'quan_1',
      provinceCode: '79',
      administrative_unit_id: 6,
    },
    {
      code: '761',
      name: 'Quận 12',
      fullName: 'Quận 12',
      codeName: 'quan_12',
      provinceCode: '79',
      administrative_unit_id: 6,
    },
    {
      code: '764',
      name: 'Quận Gò Vấp',
      fullName: 'Quận Gò Vấp',
      codeName: 'quan_go_vap',
      provinceCode: '79',
      administrative_unit_id: 6,
    },
    {
      code: '765',
      name: 'Quận Bình Thạnh',
      fullName: 'Quận Bình Thạnh',
      codeName: 'quan_binh_thanh',
      provinceCode: '79',
      administrative_unit_id: 6,
    },
    {
      code: '766',
      name: 'Quận Tân Bình',
      fullName: 'Quận Tân Bình',
      codeName: 'quan_tan_binh',
      provinceCode: '79',
      administrative_unit_id: 6,
    },
    {
      code: '767',
      name: 'Quận Tân Phú',
      fullName: 'Quận Tân Phú',
      codeName: 'quan_tan_phu',
      provinceCode: '79',
      administrative_unit_id: 6,
    },
    {
      code: '768',
      name: 'Quận Phú Nhuận',
      fullName: 'Quận Phú Nhuận',
      codeName: 'quan_phu_nhuan',
      provinceCode: '79',
      administrative_unit_id: 6,
    },
    {
      code: '769',
      name: 'Thành phố Thủ Đức',
      fullName: 'Thành phố Thủ Đức',
      codeName: 'thanh_pho_thu_duc',
      provinceCode: '79',
      administrative_unit_id: 3,
    },
    {
      code: '770',
      name: 'Quận 3',
      fullName: 'Quận 3',
      codeName: 'quan_3',
      provinceCode: '79',
      administrative_unit_id: 6,
    },
    {
      code: '771',
      name: 'Quận 10',
      fullName: 'Quận 10',
      codeName: 'quan_10',
      provinceCode: '79',
      administrative_unit_id: 6,
    },
    {
      code: '772',
      name: 'Quận 11',
      fullName: 'Quận 11',
      codeName: 'quan_11',
      provinceCode: '79',
      administrative_unit_id: 6,
    },
    {
      code: '773',
      name: 'Quận 4',
      fullName: 'Quận 4',
      codeName: 'quan_4',
      provinceCode: '79',
      administrative_unit_id: 6,
    },
    {
      code: '774',
      name: 'Quận 5',
      fullName: 'Quận 5',
      codeName: 'quan_5',
      provinceCode: '79',
      administrative_unit_id: 6,
    },
    {
      code: '775',
      name: 'Quận 6',
      fullName: 'Quận 6',
      codeName: 'quan_6',
      provinceCode: '79',
      administrative_unit_id: 6,
    },
    {
      code: '776',
      name: 'Quận 8',
      fullName: 'Quận 8',
      codeName: 'quan_8',
      provinceCode: '79',
      administrative_unit_id: 6,
    },
    {
      code: '777',
      name: 'Quận Bình Tân',
      fullName: 'Quận Bình Tân',
      codeName: 'quan_binh_tan',
      provinceCode: '79',
      administrative_unit_id: 6,
    },
    {
      code: '778',
      name: 'Quận 7',
      fullName: 'Quận 7',
      codeName: 'quan_7',
      provinceCode: '79',
      administrative_unit_id: 6,
    },
    {
      code: '783',
      name: 'Huyện Củ Chi',
      fullName: 'Huyện Củ Chi',
      codeName: 'huyen_cu_chi',
      provinceCode: '79',
      administrative_unit_id: 5,
    },
    {
      code: '784',
      name: 'Huyện Hóc Môn',
      fullName: 'Huyện Hóc Môn',
      codeName: 'huyen_hoc_mon',
      provinceCode: '79',
      administrative_unit_id: 5,
    },
    {
      code: '785',
      name: 'Huyện Bình Chánh',
      fullName: 'Huyện Bình Chánh',
      codeName: 'huyen_binh_chanh',
      provinceCode: '79',
      administrative_unit_id: 5,
    },
    {
      code: '786',
      name: 'Huyện Nhà Bè',
      fullName: 'Huyện Nhà Bè',
      codeName: 'huyen_nha_be',
      provinceCode: '79',
      administrative_unit_id: 5,
    },
    {
      code: '787',
      name: 'Huyện Cần Giờ',
      fullName: 'Huyện Cần Giờ',
      codeName: 'huyen_can_gio',
      provinceCode: '79',
      administrative_unit_id: 5,
    },

    // Hà Nội (code: 01)
    {
      code: '001',
      name: 'Quận Ba Đình',
      fullName: 'Quận Ba Đình',
      codeName: 'quan_ba_dinh',
      provinceCode: '01',
      administrative_unit_id: 6,
    },
    {
      code: '002',
      name: 'Quận Hoàn Kiếm',
      fullName: 'Quận Hoàn Kiếm',
      codeName: 'quan_hoan_kiem',
      provinceCode: '01',
      administrative_unit_id: 6,
    },
    {
      code: '003',
      name: 'Quận Tây Hồ',
      fullName: 'Quận Tây Hồ',
      codeName: 'quan_tay_ho',
      provinceCode: '01',
      administrative_unit_id: 6,
    },
    {
      code: '004',
      name: 'Quận Long Biên',
      fullName: 'Quận Long Biên',
      codeName: 'quan_long_bien',
      provinceCode: '01',
      administrative_unit_id: 6,
    },
    {
      code: '005',
      name: 'Quận Cầu Giấy',
      fullName: 'Quận Cầu Giấy',
      codeName: 'quan_cau_giay',
      provinceCode: '01',
      administrative_unit_id: 6,
    },
    {
      code: '006',
      name: 'Quận Đống Đa',
      fullName: 'Quận Đống Đa',
      codeName: 'quan_dong_da',
      provinceCode: '01',
      administrative_unit_id: 6,
    },
    {
      code: '007',
      name: 'Quận Hai Bà Trưng',
      fullName: 'Quận Hai Bà Trưng',
      codeName: 'quan_hai_ba_trung',
      provinceCode: '01',
      administrative_unit_id: 6,
    },
    {
      code: '008',
      name: 'Quận Hoàng Mai',
      fullName: 'Quận Hoàng Mai',
      codeName: 'quan_hoang_mai',
      provinceCode: '01',
      administrative_unit_id: 6,
    },
    {
      code: '009',
      name: 'Quận Thanh Xuân',
      fullName: 'Quận Thanh Xuân',
      codeName: 'quan_thanh_xuan',
      provinceCode: '01',
      administrative_unit_id: 6,
    },
    {
      code: '016',
      name: 'Huyện Sóc Sơn',
      fullName: 'Huyện Sóc Sơn',
      codeName: 'huyen_soc_son',
      provinceCode: '01',
      administrative_unit_id: 5,
    },
    {
      code: '017',
      name: 'Huyện Đông Anh',
      fullName: 'Huyện Đông Anh',
      codeName: 'huyen_dong_anh',
      provinceCode: '01',
      administrative_unit_id: 5,
    },
    {
      code: '018',
      name: 'Huyện Gia Lâm',
      fullName: 'Huyện Gia Lâm',
      codeName: 'huyen_gia_lam',
      provinceCode: '01',
      administrative_unit_id: 5,
    },
    {
      code: '019',
      name: 'Quận Nam Từ Liêm',
      fullName: 'Quận Nam Từ Liêm',
      codeName: 'quan_nam_tu_liem',
      provinceCode: '01',
      administrative_unit_id: 6,
    },
    {
      code: '020',
      name: 'Huyện Thanh Trì',
      fullName: 'Huyện Thanh Trì',
      codeName: 'huyen_thanh_tri',
      provinceCode: '01',
      administrative_unit_id: 5,
    },
    {
      code: '021',
      name: 'Quận Bắc Từ Liêm',
      fullName: 'Quận Bắc Từ Liêm',
      codeName: 'quan_bac_tu_liem',
      provinceCode: '01',
      administrative_unit_id: 6,
    },

    // Đà Nẵng (code: 48)
    {
      code: '490',
      name: 'Quận Liên Chiểu',
      fullName: 'Quận Liên Chiểu',
      codeName: 'quan_lien_chieu',
      provinceCode: '48',
      administrative_unit_id: 6,
    },
    {
      code: '491',
      name: 'Quận Thanh Khê',
      fullName: 'Quận Thanh Khê',
      codeName: 'quan_thanh_khe',
      provinceCode: '48',
      administrative_unit_id: 6,
    },
    {
      code: '492',
      name: 'Quận Hải Châu',
      fullName: 'Quận Hải Châu',
      codeName: 'quan_hai_chau',
      provinceCode: '48',
      administrative_unit_id: 6,
    },
    {
      code: '493',
      name: 'Quận Sơn Trà',
      fullName: 'Quận Sơn Trà',
      codeName: 'quan_son_tra',
      provinceCode: '48',
      administrative_unit_id: 6,
    },
    {
      code: '494',
      name: 'Quận Ngũ Hành Sơn',
      fullName: 'Quận Ngũ Hành Sơn',
      codeName: 'quan_ngu_hanh_son',
      provinceCode: '48',
      administrative_unit_id: 6,
    },
    {
      code: '495',
      name: 'Quận Cẩm Lệ',
      fullName: 'Quận Cẩm Lệ',
      codeName: 'quan_cam_le',
      provinceCode: '48',
      administrative_unit_id: 6,
    },
    {
      code: '497',
      name: 'Huyện Hòa Vang',
      fullName: 'Huyện Hòa Vang',
      codeName: 'huyen_hoa_vang',
      provinceCode: '48',
      administrative_unit_id: 5,
    },
    {
      code: '498',
      name: 'Huyện Hoàng Sa',
      fullName: 'Huyện Hoàng Sa',
      codeName: 'huyen_hoang_sa',
      provinceCode: '48',
      administrative_unit_id: 5,
    },

    // Cần Thơ (code: 92)
    {
      code: '916',
      name: 'Quận Ninh Kiều',
      fullName: 'Quận Ninh Kiều',
      codeName: 'quan_ninh_kieu',
      provinceCode: '92',
      administrative_unit_id: 6,
    },
    {
      code: '917',
      name: 'Quận Ô Môn',
      fullName: 'Quận Ô Môn',
      codeName: 'quan_o_mon',
      provinceCode: '92',
      administrative_unit_id: 6,
    },
    {
      code: '918',
      name: 'Quận Bình Thuỷ',
      fullName: 'Quận Bình Thuỷ',
      codeName: 'quan_binh_thuy',
      provinceCode: '92',
      administrative_unit_id: 6,
    },
    {
      code: '919',
      name: 'Quận Cái Răng',
      fullName: 'Quận Cái Răng',
      codeName: 'quan_cai_rang',
      provinceCode: '92',
      administrative_unit_id: 6,
    },
    {
      code: '923',
      name: 'Quận Thốt Nốt',
      fullName: 'Quận Thốt Nốt',
      codeName: 'quan_thot_not',
      provinceCode: '92',
      administrative_unit_id: 6,
    },
    {
      code: '924',
      name: 'Huyện Vĩnh Thạnh',
      fullName: 'Huyện Vĩnh Thạnh',
      codeName: 'huyen_vinh_thanh',
      provinceCode: '92',
      administrative_unit_id: 5,
    },
    {
      code: '925',
      name: 'Huyện Cờ Đỏ',
      fullName: 'Huyện Cờ Đỏ',
      codeName: 'huyen_co_do',
      provinceCode: '92',
      administrative_unit_id: 5,
    },
    {
      code: '926',
      name: 'Huyện Phong Điền',
      fullName: 'Huyện Phong Điền',
      codeName: 'huyen_phong_dien',
      provinceCode: '92',
      administrative_unit_id: 5,
    },
    {
      code: '927',
      name: 'Huyện Thới Lai',
      fullName: 'Huyện Thới Lai',
      codeName: 'huyen_thoi_lai',
      provinceCode: '92',
      administrative_unit_id: 5,
    },
  ];

  for (const district of districts) {
    await prisma.districts.upsert({
      where: { code: district.code },
      update: district,
      create: district,
    });
  }

  console.log(`✅ Created ${districts.length} districts`);
}

main()
  .catch((e) => {
    console.error('❌ Error seeding districts:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
