const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

async function main() {
  console.log('🏞️ Seeding Provinces...');

  const provinces = [
    // Đông Bắc Bộ (Region 1)
    {
      code: '01',
      name: 'Hà Nội',
      fullName: 'Thành phố Hà Nội',
      codeName: 'ha_noi',
      administrative_unit_id: 1,
      administrative_region_id: 3,
    },
    {
      code: '02',
      name: 'Hà Giang',
      fullName: 'Tỉnh Hà Giang',
      codeName: 'ha_giang',
      administrative_unit_id: 2,
      administrative_region_id: 1,
    },
    {
      code: '04',
      name: 'Cao Bằng',
      fullName: 'Tỉnh Cao Bằng',
      codeName: 'cao_bang',
      administrative_unit_id: 2,
      administrative_region_id: 1,
    },
    {
      code: '06',
      name: 'Bắc Kạn',
      fullName: 'Tỉnh Bắc Kạn',
      codeName: 'bac_kan',
      administrative_unit_id: 2,
      administrative_region_id: 1,
    },
    {
      code: '08',
      name: 'Tuyên Quang',
      fullName: 'Tỉnh Tuyên Quang',
      codeName: 'tuyen_quang',
      administrative_unit_id: 2,
      administrative_region_id: 1,
    },
    {
      code: '10',
      name: 'Lào Cai',
      fullName: 'Tỉnh Lào Cai',
      codeName: 'lao_cai',
      administrative_unit_id: 2,
      administrative_region_id: 2,
    },
    {
      code: '11',
      name: 'Điện Biên',
      fullName: 'Tỉnh Điện Biên',
      codeName: 'dien_bien',
      administrative_unit_id: 2,
      administrative_region_id: 2,
    },
    {
      code: '12',
      name: 'Lai Châu',
      fullName: 'Tỉnh Lai Châu',
      codeName: 'lai_chau',
      administrative_unit_id: 2,
      administrative_region_id: 2,
    },
    {
      code: '14',
      name: 'Sơn La',
      fullName: 'Tỉnh Sơn La',
      codeName: 'son_la',
      administrative_unit_id: 2,
      administrative_region_id: 2,
    },
    {
      code: '15',
      name: 'Yên Bái',
      fullName: 'Tỉnh Yên Bái',
      codeName: 'yen_bai',
      administrative_unit_id: 2,
      administrative_region_id: 2,
    },
    {
      code: '17',
      name: 'Hoà Bình',
      fullName: 'Tỉnh Hoà Bình',
      codeName: 'hoa_binh',
      administrative_unit_id: 2,
      administrative_region_id: 2,
    },
    {
      code: '19',
      name: 'Thái Nguyên',
      fullName: 'Tỉnh Thái Nguyên',
      codeName: 'thai_nguyen',
      administrative_unit_id: 2,
      administrative_region_id: 1,
    },
    {
      code: '20',
      name: 'Lạng Sơn',
      fullName: 'Tỉnh Lạng Sơn',
      codeName: 'lang_son',
      administrative_unit_id: 2,
      administrative_region_id: 1,
    },
    {
      code: '22',
      name: 'Quảng Ninh',
      fullName: 'Tỉnh Quảng Ninh',
      codeName: 'quang_ninh',
      administrative_unit_id: 2,
      administrative_region_id: 1,
    },
    {
      code: '24',
      name: 'Bắc Giang',
      fullName: 'Tỉnh Bắc Giang',
      codeName: 'bac_giang',
      administrative_unit_id: 2,
      administrative_region_id: 1,
    },
    {
      code: '25',
      name: 'Phú Thọ',
      fullName: 'Tỉnh Phú Thọ',
      codeName: 'phu_tho',
      administrative_unit_id: 2,
      administrative_region_id: 1,
    },
    {
      code: '26',
      name: 'Vĩnh Phúc',
      fullName: 'Tỉnh Vĩnh Phúc',
      codeName: 'vinh_phuc',
      administrative_unit_id: 2,
      administrative_region_id: 3,
    },
    {
      code: '27',
      name: 'Bắc Ninh',
      fullName: 'Tỉnh Bắc Ninh',
      codeName: 'bac_ninh',
      administrative_unit_id: 2,
      administrative_region_id: 3,
    },
    {
      code: '30',
      name: 'Hải Dương',
      fullName: 'Tỉnh Hải Dương',
      codeName: 'hai_duong',
      administrative_unit_id: 2,
      administrative_region_id: 3,
    },
    {
      code: '31',
      name: 'Hải Phòng',
      fullName: 'Thành phố Hải Phòng',
      codeName: 'hai_phong',
      administrative_unit_id: 1,
      administrative_region_id: 3,
    },
    {
      code: '33',
      name: 'Hưng Yên',
      fullName: 'Tỉnh Hưng Yên',
      codeName: 'hung_yen',
      administrative_unit_id: 2,
      administrative_region_id: 3,
    },
    {
      code: '34',
      name: 'Thái Bình',
      fullName: 'Tỉnh Thái Bình',
      codeName: 'thai_binh',
      administrative_unit_id: 2,
      administrative_region_id: 3,
    },
    {
      code: '35',
      name: 'Hà Nam',
      fullName: 'Tỉnh Hà Nam',
      codeName: 'ha_nam',
      administrative_unit_id: 2,
      administrative_region_id: 3,
    },
    {
      code: '36',
      name: 'Nam Định',
      fullName: 'Tỉnh Nam Định',
      codeName: 'nam_dinh',
      administrative_unit_id: 2,
      administrative_region_id: 3,
    },
    {
      code: '37',
      name: 'Ninh Bình',
      fullName: 'Tỉnh Ninh Bình',
      codeName: 'ninh_binh',
      administrative_unit_id: 2,
      administrative_region_id: 3,
    },

    // Bắc Trung Bộ (Region 4)
    {
      code: '38',
      name: 'Thanh Hóa',
      fullName: 'Tỉnh Thanh Hóa',
      codeName: 'thanh_hoa',
      administrative_unit_id: 2,
      administrative_region_id: 4,
    },
    {
      code: '40',
      name: 'Nghệ An',
      fullName: 'Tỉnh Nghệ An',
      codeName: 'nghe_an',
      administrative_unit_id: 2,
      administrative_region_id: 4,
    },
    {
      code: '42',
      name: 'Hà Tĩnh',
      fullName: 'Tỉnh Hà Tĩnh',
      codeName: 'ha_tinh',
      administrative_unit_id: 2,
      administrative_region_id: 4,
    },
    {
      code: '44',
      name: 'Quảng Bình',
      fullName: 'Tỉnh Quảng Bình',
      codeName: 'quang_binh',
      administrative_unit_id: 2,
      administrative_region_id: 4,
    },
    {
      code: '45',
      name: 'Quảng Trị',
      fullName: 'Tỉnh Quảng Trị',
      codeName: 'quang_tri',
      administrative_unit_id: 2,
      administrative_region_id: 4,
    },
    {
      code: '46',
      name: 'Thừa Thiên Huế',
      fullName: 'Tỉnh Thừa Thiên Huế',
      codeName: 'thua_thien_hue',
      administrative_unit_id: 2,
      administrative_region_id: 4,
    },

    // Duyên hải Nam Trung Bộ (Region 5)
    {
      code: '48',
      name: 'Đà Nẵng',
      fullName: 'Thành phố Đà Nẵng',
      codeName: 'da_nang',
      administrative_unit_id: 1,
      administrative_region_id: 5,
    },
    {
      code: '49',
      name: 'Quảng Nam',
      fullName: 'Tỉnh Quảng Nam',
      codeName: 'quang_nam',
      administrative_unit_id: 2,
      administrative_region_id: 5,
    },
    {
      code: '51',
      name: 'Quảng Ngãi',
      fullName: 'Tỉnh Quảng Ngãi',
      codeName: 'quang_ngai',
      administrative_unit_id: 2,
      administrative_region_id: 5,
    },
    {
      code: '52',
      name: 'Bình Định',
      fullName: 'Tỉnh Bình Định',
      codeName: 'binh_dinh',
      administrative_unit_id: 2,
      administrative_region_id: 5,
    },
    {
      code: '54',
      name: 'Phú Yên',
      fullName: 'Tỉnh Phú Yên',
      codeName: 'phu_yen',
      administrative_unit_id: 2,
      administrative_region_id: 5,
    },
    {
      code: '56',
      name: 'Khánh Hòa',
      fullName: 'Tỉnh Khánh Hòa',
      codeName: 'khanh_hoa',
      administrative_unit_id: 2,
      administrative_region_id: 5,
    },
    {
      code: '58',
      name: 'Ninh Thuận',
      fullName: 'Tỉnh Ninh Thuận',
      codeName: 'ninh_thuan',
      administrative_unit_id: 2,
      administrative_region_id: 5,
    },
    {
      code: '60',
      name: 'Bình Thuận',
      fullName: 'Tỉnh Bình Thuận',
      codeName: 'binh_thuan',
      administrative_unit_id: 2,
      administrative_region_id: 5,
    },

    // Tây Nguyên (Region 6)
    {
      code: '62',
      name: 'Kon Tum',
      fullName: 'Tỉnh Kon Tum',
      codeName: 'kon_tum',
      administrative_unit_id: 2,
      administrative_region_id: 6,
    },
    {
      code: '64',
      name: 'Gia Lai',
      fullName: 'Tỉnh Gia Lai',
      codeName: 'gia_lai',
      administrative_unit_id: 2,
      administrative_region_id: 6,
    },
    {
      code: '66',
      name: 'Đắk Lắk',
      fullName: 'Tỉnh Đắk Lắk',
      codeName: 'dak_lak',
      administrative_unit_id: 2,
      administrative_region_id: 6,
    },
    {
      code: '67',
      name: 'Đắk Nông',
      fullName: 'Tỉnh Đắk Nông',
      codeName: 'dak_nong',
      administrative_unit_id: 2,
      administrative_region_id: 6,
    },
    {
      code: '68',
      name: 'Lâm Đồng',
      fullName: 'Tỉnh Lâm Đồng',
      codeName: 'lam_dong',
      administrative_unit_id: 2,
      administrative_region_id: 6,
    },

    // Đông Nam Bộ (Region 7)
    {
      code: '70',
      name: 'Bình Phước',
      fullName: 'Tỉnh Bình Phước',
      codeName: 'binh_phuoc',
      administrative_unit_id: 2,
      administrative_region_id: 7,
    },
    {
      code: '72',
      name: 'Tây Ninh',
      fullName: 'Tỉnh Tây Ninh',
      codeName: 'tay_ninh',
      administrative_unit_id: 2,
      administrative_region_id: 7,
    },
    {
      code: '74',
      name: 'Bình Dương',
      fullName: 'Tỉnh Bình Dương',
      codeName: 'binh_duong',
      administrative_unit_id: 2,
      administrative_region_id: 7,
    },
    {
      code: '75',
      name: 'Đồng Nai',
      fullName: 'Tỉnh Đồng Nai',
      codeName: 'dong_nai',
      administrative_unit_id: 2,
      administrative_region_id: 7,
    },
    {
      code: '77',
      name: 'Bà Rịa - Vũng Tàu',
      fullName: 'Tỉnh Bà Rịa - Vũng Tàu',
      codeName: 'ba_ria_vung_tau',
      administrative_unit_id: 2,
      administrative_region_id: 7,
    },
    {
      code: '79',
      name: 'Hồ Chí Minh',
      fullName: 'Thành phố Hồ Chí Minh',
      codeName: 'ho_chi_minh',
      administrative_unit_id: 1,
      administrative_region_id: 7,
    },

    // Đồng bằng sông Cửu Long (Region 8)
    {
      code: '80',
      name: 'Long An',
      fullName: 'Tỉnh Long An',
      codeName: 'long_an',
      administrative_unit_id: 2,
      administrative_region_id: 8,
    },
    {
      code: '82',
      name: 'Tiền Giang',
      fullName: 'Tỉnh Tiền Giang',
      codeName: 'tien_giang',
      administrative_unit_id: 2,
      administrative_region_id: 8,
    },
    {
      code: '83',
      name: 'Bến Tre',
      fullName: 'Tỉnh Bến Tre',
      codeName: 'ben_tre',
      administrative_unit_id: 2,
      administrative_region_id: 8,
    },
    {
      code: '84',
      name: 'Trà Vinh',
      fullName: 'Tỉnh Trà Vinh',
      codeName: 'tra_vinh',
      administrative_unit_id: 2,
      administrative_region_id: 8,
    },
    {
      code: '86',
      name: 'Vĩnh Long',
      fullName: 'Tỉnh Vĩnh Long',
      codeName: 'vinh_long',
      administrative_unit_id: 2,
      administrative_region_id: 8,
    },
    {
      code: '87',
      name: 'Đồng Tháp',
      fullName: 'Tỉnh Đồng Tháp',
      codeName: 'dong_thap',
      administrative_unit_id: 2,
      administrative_region_id: 8,
    },
    {
      code: '89',
      name: 'An Giang',
      fullName: 'Tỉnh An Giang',
      codeName: 'an_giang',
      administrative_unit_id: 2,
      administrative_region_id: 8,
    },
    {
      code: '91',
      name: 'Kiên Giang',
      fullName: 'Tỉnh Kiên Giang',
      codeName: 'kien_giang',
      administrative_unit_id: 2,
      administrative_region_id: 8,
    },
    {
      code: '92',
      name: 'Cần Thơ',
      fullName: 'Thành phố Cần Thơ',
      codeName: 'can_tho',
      administrative_unit_id: 1,
      administrative_region_id: 8,
    },
    {
      code: '93',
      name: 'Hậu Giang',
      fullName: 'Tỉnh Hậu Giang',
      codeName: 'hau_giang',
      administrative_unit_id: 2,
      administrative_region_id: 8,
    },
    {
      code: '94',
      name: 'Sóc Trăng',
      fullName: 'Tỉnh Sóc Trăng',
      codeName: 'soc_trang',
      administrative_unit_id: 2,
      administrative_region_id: 8,
    },
    {
      code: '95',
      name: 'Bạc Liêu',
      fullName: 'Tỉnh Bạc Liêu',
      codeName: 'bac_lieu',
      administrative_unit_id: 2,
      administrative_region_id: 8,
    },
    {
      code: '96',
      name: 'Cà Mau',
      fullName: 'Tỉnh Cà Mau',
      codeName: 'ca_mau',
      administrative_unit_id: 2,
      administrative_region_id: 8,
    },
  ];

  for (const province of provinces) {
    await prisma.provinces.upsert({
      where: { code: province.code },
      update: province,
      create: province,
    });
  }

  console.log(`✅ Created ${provinces.length} provinces`);
}

main()
  .catch((e) => {
    console.error('❌ Error seeding provinces:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
