const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

async function main() {
  console.log('🏠 Seeding Wards...');

  const wards = [
    // Quận 1, TP.HCM (district code: 760)
    {
      code: '26734',
      name: 'Phường Tân Định',
      nameEn: 'Tan Dinh Ward',
      fullName: 'Phường Tân Định',
      fullNameEn: 'Tan Dinh Ward',
      codeName: 'phuong_tan_dinh',
      districtCode: '760',
      administrative_unit_id: 7,
    },
    {
      code: '26737',
      name: 'Phường Đa Kao',
      nameEn: 'Da Kao Ward',
      fullName: 'Phường Đa Kao',
      fullNameEn: 'Da Kao Ward',
      codeName: 'phuong_da_kao',
      districtCode: '760',
      administrative_unit_id: 7,
    },
    {
      code: '26740',
      name: 'Phường Bến Nghé',
      nameEn: 'Ben Nghe Ward',
      fullName: 'Phường Bến Nghé',
      fullNameEn: 'Ben Nghe Ward',
      codeName: 'phuong_ben_nghe',
      districtCode: '760',
      administrative_unit_id: 7,
    },
    {
      code: '26743',
      name: 'Phường Bến Thành',
      nameEn: 'Ben Thanh Ward',
      fullName: 'Phường Bến Thành',
      fullNameEn: 'Ben Thanh Ward',
      codeName: 'phuong_ben_thanh',
      districtCode: '760',
      administrative_unit_id: 7,
    },
    {
      code: '26746',
      name: 'Phường Nguyễn Thái Bình',
      nameEn: 'Nguyen Thai Binh Ward',
      fullName: 'Phường Nguyễn Thái Bình',
      fullNameEn: 'Nguyen Thai Binh Ward',
      codeName: 'phuong_nguyen_thai_binh',
      districtCode: '760',
      administrative_unit_id: 7,
    },
    {
      code: '26749',
      name: 'Phường Phạm Ngũ Lão',
      nameEn: 'Pham Ngu Lao Ward',
      fullName: 'Phường Phạm Ngũ Lão',
      fullNameEn: 'Pham Ngu Lao Ward',
      codeName: 'phuong_pham_ngu_lao',
      districtCode: '760',
      administrative_unit_id: 7,
    },
    {
      code: '26752',
      name: 'Phường Cầu Ông Lãnh',
      nameEn: 'Cau Ong Lanh Ward',
      fullName: 'Phường Cầu Ông Lãnh',
      fullNameEn: 'Cau Ong Lanh Ward',
      codeName: 'phuong_cau_ong_lanh',
      districtCode: '760',
      administrative_unit_id: 7,
    },
    {
      code: '26755',
      name: 'Phường Cô Giang',
      nameEn: 'Co Giang Ward',
      fullName: 'Phường Cô Giang',
      fullNameEn: 'Co Giang Ward',
      codeName: 'phuong_co_giang',
      districtCode: '760',
      administrative_unit_id: 7,
    },
    {
      code: '26758',
      name: 'Phường Nguyễn Cư Trinh',
      nameEn: 'Nguyen Cu Trinh Ward',
      fullName: 'Phường Nguyễn Cư Trinh',
      fullNameEn: 'Nguyen Cu Trinh Ward',
      codeName: 'phuong_nguyen_cu_trinh',
      districtCode: '760',
      administrative_unit_id: 7,
    },
    {
      code: '26761',
      name: 'Phường Cầu Kho',
      nameEn: 'Cau Kho Ward',
      fullName: 'Phường Cầu Kho',
      fullNameEn: 'Cau Kho Ward',
      codeName: 'phuong_cau_kho',
      districtCode: '760',
      administrative_unit_id: 7,
    },

    // Quận Gò Vấp, TP.HCM (district code: 764)
    {
      code: '26857',
      name: 'Phường 1',
      nameEn: 'Ward 1',
      fullName: 'Phường 1',
      fullNameEn: 'Ward 1',
      codeName: 'phuong_1',
      districtCode: '764',
      administrative_unit_id: 7,
    },
    {
      code: '26860',
      name: 'Phường 3',
      nameEn: 'Ward 3',
      fullName: 'Phường 3',
      fullNameEn: 'Ward 3',
      codeName: 'phuong_3',
      districtCode: '764',
      administrative_unit_id: 7,
    },
    {
      code: '26863',
      name: 'Phường 4',
      nameEn: 'Ward 4',
      fullName: 'Phường 4',
      fullNameEn: 'Ward 4',
      codeName: 'phuong_4',
      districtCode: '764',
      administrative_unit_id: 7,
    },
    {
      code: '26866',
      name: 'Phường 5',
      nameEn: 'Ward 5',
      fullName: 'Phường 5',
      fullNameEn: 'Ward 5',
      codeName: 'phuong_5',
      districtCode: '764',
      administrative_unit_id: 7,
    },
    {
      code: '26869',
      name: 'Phường 6',
      nameEn: 'Ward 6',
      fullName: 'Phường 6',
      fullNameEn: 'Ward 6',
      codeName: 'phuong_6',
      districtCode: '764',
      administrative_unit_id: 7,
    },
    {
      code: '26872',
      name: 'Phường 7',
      nameEn: 'Ward 7',
      fullName: 'Phường 7',
      fullNameEn: 'Ward 7',
      codeName: 'phuong_7',
      districtCode: '764',
      administrative_unit_id: 7,
    },
    {
      code: '26875',
      name: 'Phường 8',
      nameEn: 'Ward 8',
      fullName: 'Phường 8',
      fullNameEn: 'Ward 8',
      codeName: 'phuong_8',
      districtCode: '764',
      administrative_unit_id: 7,
    },
    {
      code: '26878',
      name: 'Phường 9',
      nameEn: 'Ward 9',
      fullName: 'Phường 9',
      fullNameEn: 'Ward 9',
      codeName: 'phuong_9',
      districtCode: '764',
      administrative_unit_id: 7,
    },
    {
      code: '26881',
      name: 'Phường 10',
      nameEn: 'Ward 10',
      fullName: 'Phường 10',
      fullNameEn: 'Ward 10',
      codeName: 'phuong_10',
      districtCode: '764',
      administrative_unit_id: 7,
    },
    {
      code: '26884',
      name: 'Phường 11',
      nameEn: 'Ward 11',
      fullName: 'Phường 11',
      fullNameEn: 'Ward 11',
      codeName: 'phuong_11',
      districtCode: '764',
      administrative_unit_id: 7,
    },

    // Quận Ba Đình, Hà Nội (district code: 001)
    {
      code: '00001',
      name: 'Phường Phúc Xá',
      nameEn: 'Phuc Xa Ward',
      fullName: 'Phường Phúc Xá',
      fullNameEn: 'Phuc Xa Ward',
      codeName: 'phuong_phuc_xa',
      districtCode: '001',
      administrative_unit_id: 7,
    },
    {
      code: '00004',
      name: 'Phường Trúc Bạch',
      nameEn: 'Truc Bach Ward',
      fullName: 'Phường Trúc Bạch',
      fullNameEn: 'Truc Bach Ward',
      codeName: 'phuong_truc_bach',
      districtCode: '001',
      administrative_unit_id: 7,
    },
    {
      code: '00006',
      name: 'Phường Vĩnh Phúc',
      nameEn: 'Vinh Phuc Ward',
      fullName: 'Phường Vĩnh Phúc',
      fullNameEn: 'Vinh Phuc Ward',
      codeName: 'phuong_vinh_phuc',
      districtCode: '001',
      administrative_unit_id: 7,
    },
    {
      code: '00007',
      name: 'Phường Cống Vị',
      nameEn: 'Cong Vi Ward',
      fullName: 'Phường Cống Vị',
      fullNameEn: 'Cong Vi Ward',
      codeName: 'phuong_cong_vi',
      districtCode: '001',
      administrative_unit_id: 7,
    },
    {
      code: '00008',
      name: 'Phường Liễu Giai',
      nameEn: 'Lieu Giai Ward',
      fullName: 'Phường Liễu Giai',
      fullNameEn: 'Lieu Giai Ward',
      codeName: 'phuong_lieu_giai',
      districtCode: '001',
      administrative_unit_id: 7,
    },
    {
      code: '00010',
      name: 'Phường Nguyễn Trung Trực',
      nameEn: 'Nguyen Trung Truc Ward',
      fullName: 'Phường Nguyễn Trung Trực',
      fullNameEn: 'Nguyen Trung Truc Ward',
      codeName: 'phuong_nguyen_trung_truc',
      districtCode: '001',
      administrative_unit_id: 7,
    },
    {
      code: '00013',
      name: 'Phường Quán Thánh',
      nameEn: 'Quan Thanh Ward',
      fullName: 'Phường Quán Thánh',
      fullNameEn: 'Quan Thanh Ward',
      codeName: 'phuong_quan_thanh',
      districtCode: '001',
      administrative_unit_id: 7,
    },
    {
      code: '00016',
      name: 'Phường Ngọc Hà',
      nameEn: 'Ngoc Ha Ward',
      fullName: 'Phường Ngọc Hà',
      fullNameEn: 'Ngoc Ha Ward',
      codeName: 'phuong_ngoc_ha',
      districtCode: '001',
      administrative_unit_id: 7,
    },
    {
      code: '00019',
      name: 'Phường Điện Biên',
      nameEn: 'Dien Bien Ward',
      fullName: 'Phường Điện Biên',
      fullNameEn: 'Dien Bien Ward',
      codeName: 'phuong_dien_bien',
      districtCode: '001',
      administrative_unit_id: 7,
    },
    {
      code: '00022',
      name: 'Phường Đội Cấn',
      nameEn: 'Doi Can Ward',
      fullName: 'Phường Đội Cấn',
      fullNameEn: 'Doi Can Ward',
      codeName: 'phuong_doi_can',
      districtCode: '001',
      administrative_unit_id: 7,
    },

    // Quận Hoàn Kiếm, Hà Nội (district code: 002)
    {
      code: '00025',
      name: 'Phường Phúc Tân',
      nameEn: 'Phuc Tan Ward',
      fullName: 'Phường Phúc Tân',
      fullNameEn: 'Phuc Tan Ward',
      codeName: 'phuong_phuc_tan',
      districtCode: '002',
      administrative_unit_id: 7,
    },
    {
      code: '00028',
      name: 'Phường Đồng Xuân',
      nameEn: 'Dong Xuan Ward',
      fullName: 'Phường Đồng Xuân',
      fullNameEn: 'Dong Xuan Ward',
      codeName: 'phuong_dong_xuan',
      districtCode: '002',
      administrative_unit_id: 7,
    },
    {
      code: '00031',
      name: 'Phường Hàng Mã',
      nameEn: 'Hang Ma Ward',
      fullName: 'Phường Hàng Mã',
      fullNameEn: 'Hang Ma Ward',
      codeName: 'phuong_hang_ma',
      districtCode: '002',
      administrative_unit_id: 7,
    },
    {
      code: '00034',
      name: 'Phường Hàng Buồm',
      nameEn: 'Hang Buom Ward',
      fullName: 'Phường Hàng Buồm',
      fullNameEn: 'Hang Buom Ward',
      codeName: 'phuong_hang_buom',
      districtCode: '002',
      administrative_unit_id: 7,
    },
    {
      code: '00037',
      name: 'Phường Hàng Đào',
      nameEn: 'Hang Dao Ward',
      fullName: 'Phường Hàng Đào',
      fullNameEn: 'Hang Dao Ward',
      codeName: 'phuong_hang_dao',
      districtCode: '002',
      administrative_unit_id: 7,
    },
    {
      code: '00040',
      name: 'Phường Hàng Bồ',
      nameEn: 'Hang Bo Ward',
      fullName: 'Phường Hàng Bồ',
      fullNameEn: 'Hang Bo Ward',
      codeName: 'phuong_hang_bo',
      districtCode: '002',
      administrative_unit_id: 7,
    },
    {
      code: '00043',
      name: 'Phường Cửa Đông',
      nameEn: 'Cua Dong Ward',
      fullName: 'Phường Cửa Đông',
      fullNameEn: 'Cua Dong Ward',
      codeName: 'phuong_cua_dong',
      districtCode: '002',
      administrative_unit_id: 7,
    },
    {
      code: '00046',
      name: 'Phường Lý Thái Tổ',
      nameEn: 'Ly Thai To Ward',
      fullName: 'Phường Lý Thái Tổ',
      fullNameEn: 'Ly Thai To Ward',
      codeName: 'phuong_ly_thai_to',
      districtCode: '002',
      administrative_unit_id: 7,
    },
    {
      code: '00049',
      name: 'Phường Hàng Bạc',
      nameEn: 'Hang Bac Ward',
      fullName: 'Phường Hàng Bạc',
      fullNameEn: 'Hang Bac Ward',
      codeName: 'phuong_hang_bac',
      districtCode: '002',
      administrative_unit_id: 7,
    },
    {
      code: '00052',
      name: 'Phường Hàng Gai',
      nameEn: 'Hang Gai Ward',
      fullName: 'Phường Hàng Gai',
      fullNameEn: 'Hang Gai Ward',
      codeName: 'phuong_hang_gai',
      districtCode: '002',
      administrative_unit_id: 7,
    },

    // Huyện Củ Chi, TP.HCM (district code: 783)
    {
      code: '27259',
      name: 'Thị trấn Củ Chi',
      nameEn: 'Cu Chi Town',
      fullName: 'Thị trấn Củ Chi',
      fullNameEn: 'Cu Chi Town',
      codeName: 'thi_tran_cu_chi',
      districtCode: '783',
      administrative_unit_id: 8,
    },
    {
      code: '27262',
      name: 'Xã Phú Mỹ Hưng',
      nameEn: 'Phu My Hung Commune',
      fullName: 'Xã Phú Mỹ Hưng',
      fullNameEn: 'Phu My Hung Commune',
      codeName: 'xa_phu_my_hung',
      districtCode: '783',
      administrative_unit_id: 9,
    },
    {
      code: '27265',
      name: 'Xã An Phú',
      nameEn: 'An Phu Commune',
      fullName: 'Xã An Phú',
      fullNameEn: 'An Phu Commune',
      codeName: 'xa_an_phu',
      districtCode: '783',
      administrative_unit_id: 9,
    },
    {
      code: '27268',
      name: 'Xã Trung Lập Thượng',
      nameEn: 'Trung Lap Thuong Commune',
      fullName: 'Xã Trung Lập Thượng',
      fullNameEn: 'Trung Lap Thuong Commune',
      codeName: 'xa_trung_lap_thuong',
      districtCode: '783',
      administrative_unit_id: 9,
    },
    {
      code: '27271',
      name: 'Xã An Nhơn Tây',
      nameEn: 'An Nhon Tay Commune',
      fullName: 'Xã An Nhơn Tây',
      fullNameEn: 'An Nhon Tay Commune',
      codeName: 'xa_an_nhon_tay',
      districtCode: '783',
      administrative_unit_id: 9,
    },
  ];

  for (const ward of wards) {
    await prisma.wards.upsert({
      where: { code: ward.code },
      update: ward,
      create: ward,
    });
  }

  console.log(`✅ Created ${wards.length} wards`);
}

main()
  .catch((e) => {
    console.error('❌ Error seeding wards:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
